using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace P3.FundamentalData.API.Models
{
    public class FullFinancilalStatementAsReported
    {
        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();

        [Required]
        [Column("SymName")]
        public string Symbol { get; set; }

        [Required]
        [Column("dtDate", TypeName = "smalldatetime")]
        public DateTime Date { get; set; }
        [Required]
		public string Period { get; set; }

        public int numberOfSignificantVendors  {get; set; }
        public int a20132021DebtIssuancesMember {get; set; }
        public double? FederalIncomeTaxExpenseBenefitContinuingOperations { get; set; }
        public double? OtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentNetOfTax { get; set; }
        public double? DeferredTaxAssetsLiabilitiesNet { get; set; }
        public int debtInstrumentMaturityYearRangeStart {get; set; }
        public double? OtherNonCashIncomeExpense { get; set; }
        public long? WeightedAverageNumberOfDilutedSharesOutstanding { get; set; }
        public long? ShareBasedCompensationArrangementByShareBasedPaymentAwardEquityInstrumentsOtherThanOptionsNonvestedNumber { get; set; }
        public long? MarketAbleSecuritiesCurrent { get; set; }
        public string NoTradingSymbolFlag { get; set; }
        public double? IncomeLossFromContinuingOperationsBeforeIncomeTaxesForeign { get; set; }
        public string CrossCurrencyInterestRateContractMember { get; set; }
        public long? DeferredTaxLiabilitiesOther { get; set; }
        public long? DeferredTaxAssetsOther { get; set; }
        public string MaximumLengthOfTimeForeignCurrencyCashFlowHedge { get; set; }
        public long? ProceedsFromRepaymentsOfShortTermDebtMaturingInThreeMonthsOrLess { get; set; }
        public long? ProceedsFromRepaymentsOfShortTermDebtMaturingInMoreThanThreeMonths { get; set; }
        public long? IncomeTaxReconciliationTaxCreditsResearch { get; set; }
        public long? FinanceLeaseLiabilityPaymentsDueYearFour { get; set; }
        public int? IncreaseDecreaseInOtherOperatingAssets { get; set; }
        public double? CostOfGoodsAndServicesSold { get; set; }
        public double? UnRecordedUnconditionalPurchaseObligationBalanceOnFourthAnniversary { get; set; }
        public double financeLeaseLiabilityPaymentsDueYearThree { get; set; }
        public int tradeAccountsReceivableMember { get; set; }
        public double lesseeOperatingAndFinanceLeaseLiabilityToBePaidYearFive { get; set; }
        public double derivativeLiabilitiesReductionForMasternettingArrangementsIncludingTheEffectsOfCollateral { get; set; }
        public double grossProfit { get; set; }
        public int cashMember { get; set; }
        public double incomeTaxesPaidNet { get; set; }
        public double operatingLeaseCost { get; set; }
        public double interestExpense { get; set; }
        public int lesseeOperatingAndFinanceLeaseLeaseNotYetCommencedPaymentsDue { get; set; }
        public double deferredTaxAssetsOtherComprehensiveLoss { get; set; }
        public double lesseeOperatingAndFinanceLeaseLiabilityToBePaidYearTwo { get; set; }
        public double incomeTaxReconciliationStateAndLocalIncomeTaxes { get; set; }
        public int financeLeaseLiabilityNonCurrent { get; set; }
        public double availableForsaleSecuritiesDebtMaturitiesSingleMaturityDate { get; set; }
        public int contractWithCustomerLiability { get; set; }
        public int financeLeaseLiability { get; set; }
        public long accumulatedOtherComprehensiveIncomeMember { get; set; }
        public int adjustmentsToAdditionalPaidInCapitalShareBasedCompensationRequisiteServicePeriodRecognitionValue { get; set; }
        public long landAndBuildingMember { get; set; }
        public int availableForSaleDebtSecuritiesAccumulatedGrossUnrealizedGainBeforeTax { get; set; }
        public double unrecognizedTaxBenefits { get; set; }
        public int increaseDecreaseInContractWithCustomerLiability { get; set; }
        public double paymentsForProceedsFromOtherInvestingActivities { get; set; }
        public string entitySmallBusiness { get; set; }
        public string lesseeOperatingAndFinanceLeaseLeaseNotYetCommencedTermOfContract { get; set; }
        public long accountsPayableCurrent { get; set; }
        public double debtInstrumentCarryingAmount { get; set; }
        public long proceedsFromMaturitiesPrepaymentsAndCallsOfAvailableForSaleSecurities { get; set; }
        public double investmentIncomeInterestAndDividend { get; set; }
        public double shareBasedCompensationArrangementBySharebasedPaymentAwardEquityInstrumentsOtherThanOptionsForFeitedInPeriod { get; set; }
        public int entityAddressPostalZipcode { get; set; }
        public double ComprehensiveIncomeNetOfTax { get; set; }
        public double LiabilitiesAndStockHoldersEquity { get; set; }
        public long DeferredIncomeTaxLiabilities { get; set; }
        public double PropertyPlantAndEquipmentGross { get; set; }
        public double LesseeOperatingLeaseLiabilityUndiscountedExcessAmount { get; set; }
        public string TradingSymbol { get; set; }
        public string X1 { get; set; }
        public string DocumentTransitionReport { get; set; }
        public string DocumentFiscalPeriodFocus { get; set; }
        public double CurrentStateAndLocalTaxExpenseBenefit { get; set; }
        public long AvailableForSaleSecuritiesDebtMaturitiesRollingYearTwoThroughFiveFairValue { get; set; }
        public decimal CommonStockDividendsPerShareDeclared { get; set; }
        public int RestrictedStockUnitsRsuMember { get; set; }
        public double OtherComprehensiveIncomeUnrealizedHoldingGainLossOnSecuritiesArisingDuringPeriodNetOfTax { get; set; }
        public double IncreaseDecreaseInOtherReceivables { get; set; }
        public double LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearOne { get; set; }
        public string DebtInstrumentTerm { get; set; }
        public double CommonStockIncludingAdditionalPaidInCapitalMember { get; set; }
        public string EntityCurrentReportingStatus { get; set; }
        public string EntityShellCompany { get; set; }
        public double SellingGeneralAndAdministrativeExpense { get; set; }
        public int AuditorFirmId { get; set; }
        public double AccumulatedOtherComprehensiveIncomeLossNetOfTax { get; set; }
        public double UnrecordedUnconditionalPurchaseObligationBalanceOnSecondAnniversary { get; set; }
        public double CurrentForeignTaxExpenseBenefit { get; set; }
        public string EntityEmergingGrowthCompany { get; set; }
        public double RestrictedInvestments { get; set; }
        public double NonOperatingIncomeExpense { get; set; }
        public string AuditorName { get; set; }
        public double EffectiveIncomeTaxRateReconciliationFdiiAmount { get; set; }
        public double DeferredTaxAssetsNet { get; set; }
        public string EntityTaxIdentificationNumber { get; set; }
        public double PropertyPlantAndEquipmentNet { get; set; }
        public double WeightedAverageNumberOfSharesOutstandingBasic { get; set; }
        public string CommonStockMember { get; set; }
        public long CommonStockSharesOutstanding { get; set; }
        public double LesseeOperatingLeaseLiabilityPaymentsDue { get; set; }
        public double IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNonControllingInterest { get; set; }
        public double UnrecordedUnconditionalPurchaseObligationBalancesheetAmount { get; set; }
        public long StockIssuedDuringPeriodValueNewIssues { get; set; }
        public long StockRepurchasedAndRetiredDuringPeriodValue { get; set; }
        public double AccountsReceivableNetCurrent { get; set; }
        public double LesseeOperatingAndFinanceLeaseLiabilityUndiscountedExcessAmount { get; set; }
        public double OtherNonOperatingIncomeExpense { get; set; }
        public double LesseeOperatingLeaseLiabilityPaymentsDueAfterYearFive { get; set; }
        public long DerivativeAssetFairValueGrossAssetIncludingNotSubjectToMasternettingArrangement { get; set; }
        public double LiabilitiesCurrent { get; set; }
        public double SharebasedCompensationArrangementBySharebasedPaymentAwardEquityInstrumentsOtherThanOptionsVestedInPeriod { get; set; }
        public int ProceedsFromPaymentsForOtherFinancingActivities { get; set; }
        public double LossContingencyEstimateOfPossibleLoss { get; set; }
        public double LongtermDebtFairValue { get; set; }
        public double PaymentsToAcquireBusinessesNetOfCashAcquired { get; set; }
        public double LesseeOperatingLeaseLiabilityPaymentsDueYearTwo { get; set; }
        public double DeferredTaxLiabilitiesOtherComprehensiveIncome { get; set; }
        public double CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents { get; set; }
        public int ProceedsFromSaleOfAvailableForSaleSecuritiesDebt { get; set; }
        public double UnrecordedUnconditionalPurchaseObligationBalanceOnFirstAnniversary { get; set; }
        public decimal DefinedContributionPlanEmployerMatchingContributionPercent { get; set; }
        public long ContractWithCustomerLiabilityCurrent { get; set; }
        public long CommonStockSharesIssued { get; set; }
        public double VariableLeaseCost { get; set; }
        public double AllocatedSharebasedCompensationExpense { get; set; }
        public int EffectiveIncomeTaxRateReconciliationTaxcutsAndJobsactOf2017Amount { get; set; }
        public decimal DebtInstrumentInterestRateStatedPercentage { get; set; }
        public decimal CommonStockParOrStatedValuePerShare { get; set; }
        public double OtherComprehensiveIncomeLossDerivativeInstrumentGainLossAfterReclassificationAndTax { get; set; }
        public long FairValueInputsLevel2Member { get; set; }
        public long DeferredTaxAssetsTaxCreditCarryForwards { get; set; }
        public long OperatingLeaseLiability { get; set; }
        public double ResearchAndDevelopmentExpense { get; set; }
        public long AvailableForSaleSecuritiesDebtSecurities { get; set; }
        public long EuropeSegmentMember { get; set; }
        public string EmployeeServiceShareBasedCompensationNonVestedAwardsTotalCompensationCostNotYetRecognizedPeriodForRecognition1 { get; set; }
        public string EntityRegistrantName { get; set; }
        public double LiabilitiesNonCurrent { get; set; }
        public double DeferredTaxLiabilitiesMinimumTaxOnForeignEarnings { get; set; }
        public double EffectiveIncomeTaxRateReconciliationShareBasedCompensationExcessTaxBenefitAmount { get; set; }
        public int NumberOfCustomersWithSignificantAccountsReceivableBalance { get; set; }
        public double LesseeOperatingLeaseLiabilityPaymentsDueYearThree { get; set; }
        public string ShareBasedCompensationArrangementByShareBasedPaymentAwardAwardVestingPeriod1 { get; set; }
        public long OperatingAndFinanceLeaseLiability { get; set; }
        public string ForeignExchangeContractMember { get; set; }
        public string DocumentType { get; set; }
        public double EmployeeServiceShareBasedCompensationTaxBenefitFromCompensationExpense { get; set; }
        public string EntityAddressStateOrProvince { get; set; }
        public int DerivativeLiabilityFairValueGrossLiabilityIncludingNotSubjectToMasternettingArrangement { get; set; }
        public int EquitySecuritiesFvniAccumulatedGrossUnrealizedLossBeforeTax { get; set; }
        public int FactorByWhichEachRsuGrantedReducesAndEachRsuCanceledOrShareWithheldForTaxesIncreasesSharesAvailableForGrant { get; set; }
        public double CashCashEquivalentsAndMarketableSecurities { get; set; }
        public long FinanceLeaseRightOfUseAsset { get; set; }
        public string CommercialPaperMember { get; set; }
        public double LongTermDebtMaturitiesRepaymentsOfPrincipalAfterYearFive { get; set; }
        public double MarketableSecuritiesNonCurrent { get; set; }
        public double Liabilities { get; set; }
        public int ForeignIncomeTaxExpenseBenefitContinuingOperations { get; set; }
        public double CashEquivalentsAndMarketableSecuritiesAccumulatedGrossUnrealizedLossBeforeTax { get; set; }
        public decimal ShortTermDebtWeightedAverageInterestRate { get; set; }
        public string ShareBasedCompensationArrangementByShareBasedPaymentAwardOfferingPeriod { get; set; }
        public DateTime DocumentPeriodEndDate { get; set; }
        public long NonTradeReceivablesCurrent { get; set; }
        public long EquitySecuritiesFvniCurrentAndNonCurrent { get; set; }
        public long OperatingLeaseLiabilityCurrent { get; set; }
        public long ProceedsFromIssuanceOfLongTermDebt { get; set; }
        public int UnrecognizedTaxBenefitsDecreasesResultingFromSettlementsWithTaxingAuthorities { get; set; }
        public long NonCurrentAssets { get; set; }
        public string AuditorLocation { get; set; }
        public int OtherLiabilitiesMember { get; set; }
        public int ShareBasedCompensation { get; set; }
        public int JapanSegmentMember { get; set; }
        public long DeferredTaxAssetsGoodwillAndIntangibleAssets { get; set; }
        public long OtherAssetsMember { get; set; }
        public long CommonStocksIncludingAdditionalPaidInCapital { get; set; }
        public int LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearThree { get; set; }
        public int LesseeOperatingLeaseLiabilityPaymentsDueNextTwelveMonths { get; set; }
        public string AmendmentFlag { get; set; }
        public long OtherLiabilitiesCurrent { get; set; }
        public long InterestPaidNet { get; set; }
        public double PaymentsToAcquirePropertyPlantAndEquipment { get; set; }
        public long AmericasSegmentMember { get; set; }
        public long AvailableForSaleSecuritiesDebtMaturitiesRollingYearSixThroughTenFairValue { get; set; }
        public long CashAndCashEquivalentsAtCarryingValue { get; set; }
        public long OtherAssetsCurrent { get; set; }
        public long UnfavorableInvestigationOutcomeEuStateAidRulesMember { get; set; }
        public string SecurityExchangeName { get; set; }
        public double InterestCostsIncurred { get; set; }
        public decimal EarningsPerShareBasic { get; set; }
        public long CommonStockSharesAuthorized { get; set; }
        public long IncreaseDecreaseInAccountsPayable { get; set; }
        public long RetainedEarningsAccumulatedDeficit { get; set; }
        public string X2 { get; set; }
        public double EmployeeStockPurchasePlanMaximumAnnualPurchasesPerEmployeeAmount { get; set; }
        public double HedgeAccountingAdjustmentsRelatedToLongTermDebt { get; set; }
        public double DeferredIncomeTaxExpenseBenefit { get; set; }
        public double OperatingIncomeLoss { get; set; }
        public int ShareBasedCompensationArrangementByShareBasedPaymentAwardEquityInstrumentsOtherThanOptionsGrantsInPeriod { get; set; }
        public int EmployeeStockMember { get; set; }
        public double AssetsCurrent { get; set; }
        public string IcfrAuditOrAttestationFlag { get; set; }
        public double NetCashProvidedByUsedInFinancingActivities { get; set; }
        public int OperatingLeaseLiabilityNonCurrent { get; set; }
        public int Dividends { get; set; }
        public string EntityInteractiveDataCurrent { get; set; }
        public double IncreaseDecreaseInAccountsReceivable { get; set; }
        public int FairValueInputsLevel1Member { get; set; }
        public int DepreciationDepletionAndAmortization { get; set; }
        public double DebtInstrumentInterestAtEffectivePercentage { get; set; }
        public int LongTermDebtCurrent { get; set; }
        public int InventoryNet { get; set; }
        public double UnrecordedUnconditionalPurchaseObligationDueAfterFiveYears { get; set; }
        public double LesseeOperatingAndFinanceLeaseLiabilityToBePaidAfterYearFive { get; set; }
        public double AvailableForSaleDebtSecuritiesAmortizedCostBasis { get; set; }
        public double OtherComprehensiveIncomeLossReclassificationAdjustmentFromAociForSaleOfSecuritiesNetOfTax { get; set; }
        public double OtherComprehensiveIncomeLossDerivativeInstrumentGainLossBeforeReClassificationAfterTax { get; set; }
        public string EntityAddressAddressline1 { get; set; }
        public double OtherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationAdjustmentNetOfTax { get; set; }
        public double CurrentFederalTaxExpenseBenefit { get; set; }
        public double DeferredTaxAssetsLeaseLiabilities { get; set; }
        public int DeferredTaxAssetsTaxCreditCarryForwardsResearch { get; set; }
        public string X3 { get; set; }
        public string PropertyPlantAndEquipmentUsefulLife { get; set; }
        public long UnrecognizedTaxBenefitsIncreasesResultingFromPriorPeriodTaxPositions { get; set; }
        public long OperatingAndFinanceLeaseRightOfUseAsset { get; set; }
        public double RevenueFromContractWithCustomerExcludingAssessedTax { get; set; }
        public double PaymentsOfDividends { get; set; }
        public long CurrentMarketableSecuritiesAndNonCurrentMarketableSecuritiesMember { get; set; }
        public string EntityVoluntaryFilers { get; set; }
        public int FourthQuarter2022DebtIssuanceMember { get; set; }
        public string EntityWellKnownSeasonedIssuer { get; set; }
        public double Cash { get; set; }
        public string Security12bTitle { get; set; }
        public long UnrecordedUnconditionalPurchaseObligationBalanceOnThirdAnniversary { get; set; }
        public long Depreciation { get; set; }
        public int CityAreaCode { get; set; }
        public int FinanceLeaseLiabilityCurrent { get; set; }
        public double DerivativeNotionalAmount { get; set; }
        public double LesseeOperatingAndFinanceLeaseLiabilityPaymentsDue { get; set; }
        public double DebtInstrumentUnamortizedDiscountPremiumAndDebtIssuanceCostsNet { get; set; }
        public double FinanceLeaseLiabilityUndiscountedExcessAmount { get; set; }
        public double OperatingLeaseRightOfUseAsset { get; set; }
        public double DeferredForeignIncomeTaxExpenseBenefit { get; set; }
        public long DeferredTaxAssetsTaxDeferredExpenseReservesAndAccruals { get; set; }
        public long StateAndLocalIncomeTaxExpenseBenefitContinuingOperations { get; set; }
        public long DeferredStateAndLocalIncomeTaxExpenseBenefit { get; set; }
        public long OtherLiabilitiesNonCurrent { get; set; }
        public double LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFour { get; set; }
        public long DeferredTaxLiabilitiesLeasingArrangements { get; set; }
        public double LesseeOperatingLeaseLiabilityPaymentsDueYearFour { get; set; }
        public string LesseeOperatingAndFinanceLeaseTermOfContract { get; set; }
        public long IncomeTaxReconciliationIncomeTaxExpenseBenefitAtFederalStatutoryIncomeTaxRate { get; set; }
        public long UnrecordedUnconditionalPurchaseObligationBalanceOnFifthAnniversary { get; set; }
        public long longTermDebtMaturitiesRepaymentsOfPrincipalInYearTwo { get; set; }
        public long increaseDecreaseInInventories { get; set; }
        public double assetsNonCurrent { get; set; }
        public double sharesPaidForTaxWithHoldingForShareBasedCompensation { get; set; }
        public long otherComprehensiveIncomeLossDerivativeInstrumentGainLossReclassificationAfterTax { get; set; }
        public decimal definedContributionPlanEmployerMatchingContributionPercentOfMatch { get; set; }
        public long otherAssetsNonCurrent { get; set; }
        public long unrecognizedTaxBenefitsIncreasesResultingFromCurrentPeriodTaxPositions { get; set; }
        public double longTermDebtMaturitiesRepaymentsOfPrincipalInNextTwelveMonths { get; set; }
        public double paymentsForRepurchaseOfCommonstock { get; set; }
        public long machineryEquipmentAndInternalUseSoftwareMember { get; set; }
        public long otherAccruedLiabilitiesNoncurrent { get; set; }
        public long employeesServiceSharebasedCompensationnOnVestedAwardsTotalCompensationCostNotYetRecognized { get; set; }
        public double netIncomeLoss { get; set; }
        public long unrecognizedTaxBenefitsThatWouldImpactEffectiveTaxRate { get; set; }
        public long decreaseInUnrecognizedTaxBenefitsIsReasonablyPossible { get; set; }
        public long interestRateContractMember { get; set; }
        public long incomeTaxReconciliationForeignIncomeTaxRateDifferential { get; set; }
        public double paymentsRelatedToTaxWithHoldingForSharebasedCompensation { get; set; }
        public double increaseDecreaseInOtherOperatingLiabilities { get; set; }
        public long commercialPaper { get; set; }
        public long stockRepurchasedAndRetiredDuringPeriodShares { get; set; }
        public long unrecognizedTaxBenefitsReductionsResultingFromLapseOfApplicableStatuteOfLimitations { get; set; }
        public long cashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect { get; set; }
        public double financeLeaseLiabilityPaymentsDueYearFive { get; set; }
        public double repaymentsOfLongTermDebt { get; set; }
        public string x4 { get; set; }
        public decimal effectiveIncomeTaxRateContinuingOperations { get; set; }
        public string localPhoneNumber { get; set; }
        public long accumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment { get; set; }
        public long proceedsFromRepaymentsOfCommercialPaper { get; set; }
        public double longTermDebtNonCurrent { get; set; }
        public string entityFileNumber { get; set; }
        public int leaseHoldImprovementsMember { get; set; }
        public int performanceObligationsInArrangements { get; set; }
        public double financeLeaseLiabilityPaymentsDueNextTwelveMonths { get; set; }
        public long repaymentsOfShortTermDebtMaturingInMoreThanThreeMonths { get; set; }
        public double deferredFederalIncomeTaxExpenseBenefit { get; set; }
        public string documentAnnualReport { get; set; }
        public decimal operatingAndFinanceLeaseWeightedAverageDiscountRatePercent { get; set; }
        public long AvailableForSaleSecuritiesDebtMaturitiesRollingAfterYearTenFairValue { get; set; }
        public long RestOfAsiapacificSegmentMember { get; set; }
        public double CashCashEquivalentsAndMarketableSecuritiesCost { get; set; }
        public long RightOfUseAssetsObtainedInExchangeForOperatingAndFinanceLeaseLiabilities { get; set; }
        public int EquitySecuritiesFvniAccumulatedGrossUnrealizedGainBeforeTax { get; set; }
        public int EntityCentralIndexKey { get; set; }
        public int IncomeTaxReconciliationOtherAdjustments { get; set; }
        public long NetCashProvidedByUsedInInvestingActivities { get; set; }
        public double OperatingLeasePayments { get; set; }
        public string RevenueRemainingPerformanceObligationExpectedTimingOfSatisfactionPeriod1 { get; set; }
        public int DebtInstrumentMaturityYearRangeEnd { get; set; }
        public double PaymentsToAcquireAvailableForSaleSecuritiesDebt { get; set; }
        public long ContractWithCustomerLiabilityRevenueRecognized { get; set; }
        public int DocumentFiscalYearFocus { get; set; }
        public decimal ShareBasedCompensationArrangementBySharebasedPaymentAwardMaximumEmployeeSubscriptionRate { get; set; }
        public string EntityIncorporationStateCountryCode { get; set; }
        public decimal SharebasedCompensationArrangementBySharebasedPaymentAwardPurchasePriceOfCommonStockPercent { get; set; }
        public long DeferredTaxAssetsValuationAllowance { get; set; }
        public long CreditConcentrationRiskMember { get; set; }
        public string EntityFilerCategory { get; set; }
        public int WeightedAverageNumberDilutedSharesOutstandingAdjustment { get; set; }
        public int NonTradeReceivableMember { get; set; }
        public string EntityAddressCityOrTown { get; set; }
        public long CurrentTermDebtAndNoncurrentTermDebtMember { get; set; }
        public int StockIssuedDuringPeriodSharesSharebasedPaymentArrangementNetOfSharesWithheldForTaxes { get; set; }
        public long LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearFour { get; set; }
        public string OperatingAndFinanceLeaseWeightedAverageRemainingLeaseTerm { get; set; }
        public long OperatingExpenses { get; set; }
        public decimal RevenueRemainingPerformanceObligationPercentage { get; set; }
        public int ShareBasedCompensationArrangementBySharebasedPaymentAwardEquityInstrumentsOtherThanOptionsAggregateIntrinsicValueNonvested { get; set; }
        public double DeferredTaxAssetsDeferredIncome { get; set; }
        public decimal EarningsPerShareDiluted { get; set; }
        public string X5 { get; set; }
        public long DeferredTaxAssetsGross { get; set; }
        public long HedgedLiabilityFairValueHedge { get; set; }
        public long HedgedAssetFairValueHedge { get; set; }
        public double AccruedIncomeTaxesNoncurrent { get; set; }
        public long RetainedEarningsMember { get; set; }
        public long CashEquivalentsAndMarketableSecuritiesAccumulatedGrossUnrealizedGainBeforeTax { get; set; }
        public decimal ConcentrationRiskPercentage1 { get; set; }
        public long? FairValueConcentrationOfRiskDerivativeFinancialInstrumentsAssets { get; set; }
        public long? DeferredTaxAssetsTaxCreditCarryForwardsForeign { get; set; }
        public double NetCashProvidedByUsedInOperatingActivities { get; set; }
        public long? ProceedsFromShortTermDebtMaturingInmoreThanThreeMonths { get; set; }
        public long? UnrecognizedTaxBenefitsDecreasesResultingFromPriorPeriodTaxPositions { get; set; }
        public long? GreaterChinaSegmentMember { get; set; }
        public double EquitySecuritiesFvniCost { get; set; }
        public double FinanceLeaseLiabilityPaymentsDue { get; set; }
        public double FinanceLeaseLiabilityPaymentsDueYearTwo { get; set; }
        public long? DerivativeFairValueOfDerivativeNet { get; set; }
        public double FinanceLeaseLiabilityPaymentsDueAfterYearFive { get; set; }
        public double LongTermDebtMaturitiesRepaymentsOfPrincipalInYearThree { get; set; }
        public long? DerivativeAssetsReductionForMasternettingArrangementsIncludingTheEffectsOfCollateral { get; set; }
        public double OtherGeneralAndAdministrativeExpense { get; set; }
        public long? LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFive { get; set; }
        [MaxLength(10)]
        public string CurrentFiscalYearEndDate { get; set; }
        public long? AdjustmentsRelatedToTaxWithHoldingForSharebasedCompensation { get; set; }
        public double LesseeOperatingLeaseLiabilityPaymentsDueYearFive { get; set; }
        public double IncomeTaxExpenseBenefit { get; set; }
        [Range(typeof(decimal), "0.00001", "99999.99999", ErrorMessage = "Value must be between 0.00001 and 99999.99999")]
        public decimal EffectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate { get; set; }
        public long? AvailableForSaleDebtSecuritiesAccumulatedGrossUnrealizedLossBeforeTax { get; set; }
        [MaxLength(50)]
        public string Assets { get; set; }
        public long? OtherComprehensiveIncomeLossNetOfTaxPortionAttribuTabletOparent { get; set; }
        public long? ShareBasedCompensationArrangementBySharebasedPaymentAwardEquityInstrumentsOtherThanOptionsVestedInPeriodTotalFairValue { get; set; }
        public long? StockholdersEquity { get; set; }
        [Required]
        public DateTime DtExecuted { get; set; }
        [Required]
        public int Flag { get; set; }
    }
}
