using Microsoft.AspNetCore.Mvc.Rendering;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Runtime.InteropServices;
using System;

namespace P3.FundamentalData.Web.Models
{
    public class Screener
    {
        public string Exchange { get; set; }
		public string Index { get; set; }
		public string Sector { get; set; }
		public string Industry { get; set; }
		public string Country { get; set; }
		public string MarketCap  { get; set; }
		public string PE  { get; set; }
		public string ForwardPE  { get; set; }
		public string PEG { get; set; }
		public string PS  { get; set; }
		public string PB  { get; set; }
		public string PriceCash  { get; set; }
		public string PriceFreeCashFlow { get; set; }
		public string EPSGrowthThisYear { get; set; }
		public string EPSGrowthNextYear { get; set; }
		public string EPSGrowthPast5Years  { get; set; }
		public string EPSGrowthNext5years  { get; set; }
		public string SalesGrowthPast5Years  { get; set; }
		public string EPSGrowthQtrOverQtr  { get; set; }
		public string SalesGrowthQtrOverQtr  { get; set; }
		public string DividendYield  { get; set; }
		public string ReturnOnAssets { get; set; }
		public string ReturnOnEquity { get; set; }
		public string ReturnOnInvestment { get; set; }
		public string CurrentRatio  { get; set; }
		public string QuickRatio  { get; set; }
		public string LTDebtEquity  { get; set; }
		public string DebtEquity  { get; set; }
		public string GrossMargin  { get; set; }
		public string OperatingMargin  { get; set; }
		public string NetProfitMargin { get; set; }
		public string PayoutRatio  { get; set; }
		public string InsiderOwnership { get; set; }
		public string InsiderTransactions { get; set; }
		public string InstitutionalOwnership { get; set; }
		public string InstitutionalTransactions { get; set; }
		public string FloatShort  { get; set; }
		public string AnalystRecom  { get; set; }
		public string OptionShort  { get; set; }
		public string EarningsDate  { get; set; }
		public string Performance { get; set; }
		public string Performance2  { get; set; }
		public string Volatility { get; set; }
		public string RSI14 { get; set; }
		public string Gap { get; set; }
		public string TwentyDaySimpleMovingAverage  { get; set; }
		public string FiftyDaySimpleMovingAverage  { get; set; }
		public string TwoHundredDaySimpleMovingAverage  { get; set; }
		public string Change { get; set; }
		public string ChangeFromOpen  { get; set; }
		public string TwentuDayHighLow  { get; set; }
		public string FiftyDayHighLow  { get; set; }
		public string FiftyTwoWeekHighLow  { get; set; }
		public string Pattern { get; set; }
		public string Candlestick { get; set; }
		public string Beta { get; set; }
		public string AverageTrueRange { get; set; }
		public string AverageVolume  { get; set; }
		public string RelativeVolume  { get; set; }
		public string CurrentVolume  { get; set; }
		public string Price { get; set; }
		public string TargetPrice  { get; set; }
		public string IPODate  { get; set; }
		public string SharesOutstanding  { get; set; }
		public string Float { get; set; }
		public string AfterHoursClose  { get; set; }
		public string AfterHoursChange  { get; set; }
        public List<SelectListItem> ExchangeList { get; set; }
		public List<SelectListItem> IndexList { get; set; }
		public SelectListItem SectorList { get; set; }
		public SelectListItem IndustryList { get; set; }
		public SelectListItem CountryList { get; set; }
		public SelectListItem MarketCapList { get; set; }
		public SelectListItem PEList { get; set; }
		public SelectListItem ForwardPEList { get; set; }
		public SelectListItem PEGList { get; set; }
		public SelectListItem PSList { get; set; }
		public SelectListItem PBList { get; set; }
		public SelectListItem PriceCashList { get; set; }
		public SelectListItem PriceFreeCashFlowList { get; set; }
		public SelectListItem EPSGrowthThisYearList { get; set; }
		public SelectListItem EPSGrowthNextYearList { get; set; }
		public SelectListItem EPSGrowthPast5YearsList { get; set; }
		public SelectListItem EPSGrowthNext5yearsList { get; set; }
		public SelectListItem SalesGrowthPast5YearsList { get; set; }
		public SelectListItem EPSGrowthQtrOverQtrList { get; set; }
		public SelectListItem SalesGrowthQtrOverQtrList { get; set; }
		public SelectListItem DividendYieldList { get; set; }
		public SelectListItem ReturnOnAssetsList { get; set; }
		public SelectListItem ReturnOnEquityList { get; set; }
		public SelectListItem ReturnOnInvestmentList { get; set; }
		public SelectListItem CurrentRatioList { get; set; }
		public SelectListItem QuickRatioList { get; set; }
		public SelectListItem LTDebtEquityList { get; set; }
		public SelectListItem DebtEquityList { get; set; }
		public SelectListItem GrossMarginList { get; set; }
		public SelectListItem OperatingMarginList { get; set; }
		public SelectListItem NetProfitMarginList { get; set; }
		public SelectListItem PayoutRatioList { get; set; }
		public SelectListItem InsiderOwnershipList { get; set; }
		public SelectListItem InsiderTransactionsList { get; set; }
		public SelectListItem InstitutionalOwnershipList { get; set; }
		public SelectListItem InstitutionalTransactionsList { get; set; }
		public SelectListItem FloatShortList { get; set; }
		public SelectListItem AnalystRecomList { get; set; }
		public SelectListItem OptionShortList { get; set; }
		public SelectListItem EarningsDateList { get; set; }
		public SelectListItem PerformanceList { get; set; }
		public SelectListItem Performance2List { get; set; }
		public SelectListItem VolatilityList { get; set; }
		public SelectListItem RSI14List { get; set; }
		public SelectListItem GapList { get; set; }
		public SelectListItem TwentyDaySimpleMovingAverageList { get; set; }
		public SelectListItem FiftyDaySimpleMovingAverageList { get; set; }
		public SelectListItem TwoHundredDaySimpleMovingAverageList { get; set; }
		public SelectListItem ChangeList { get; set; }
		public SelectListItem ChangeFromOpenList { get; set; }
		public SelectListItem TwentuDayHighLowList { get; set; }
		public SelectListItem FiftyDayHighLowList { get; set; }
		public SelectListItem FiftyTwoWeekHighLowList { get; set; }
		public SelectListItem PatternList { get; set; }
		public SelectListItem CandlestickList { get; set; }
		public SelectListItem BetaList { get; set; }
		public SelectListItem AverageTrueRangeList { get; set; }
		public SelectListItem AverageVolumeList { get; set; }
		public SelectListItem RelativeVolumeList { get; set; }
		public SelectListItem CurrentVolumeList { get; set; }
		public SelectListItem PriceList { get; set; }
		public SelectListItem TargetPriceList { get; set; }
		public SelectListItem IPODateList { get; set; }
		public SelectListItem SharesOutstandingList { get; set; }
		public SelectListItem FloatList { get; set; }
		public SelectListItem AfterHoursCloseList { get; set; }
		public SelectListItem AfterHoursChangeList { get; set; }

	}
}
